version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs # image name
    container_name: nodejs # container name
    restart: unless-stopped
    ports:
      - "8080:3000" # "host:container"
    # environment:
    #   - NODE_ENV=$NODE_ENV
    # volumes:
    #   - .:/home/node/app # "host:container"
    #   - node_modules:/home/node/app/node_modules # "host:container"
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
networks:
  default:
    external:
      name: my-test-net # this name is in the ais-one/docker-devenv project, mongodb docker-compose.yml file
