version: '3'

services:
  vcx-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARG_API_PORT: 3000
    image: nodejs # image name
    container_name: nodejs # container name
    restart: unless-stopped
    ports:
      - "3000:3000" # "host:container"
    # environment:
    #   - API_PORT=3333
    #   - NODE_ENV=development
    #   - APP_NAME=example-app
    # volumes:
    #   - .:/home/node/app # "host:container"
    #   - node_modules:/home/node/app/node_modules # "host:container"
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
networks:
  default:
    external:
      name: my-test-net # this name is in the ais-one/docker-devenv project, mongodb docker-compose.yml file
