name: Update Function

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      fn_csp:
        description: 'Cloud Service Provider - aliyun, aws, digitalocean'
        default: 'aliyun'
        required: true
      fn_servicename:
        description: 'service name'
        default: ''
        required: true
      fn_functionname:
        description: 'function name'
        default: 'fc-test-api'
        required: true
      mode:
        default: 'AK'
        description: 'Aliyun CLI Authentication mode, valid vaules are [AK|StsToken] here'
      region:
        default: 'ap-southeast-1'
        required: true
        description: 'Region of your service, e.g. ap-southeast-1'
      ak_id:
        description: 'Access key ID of your account (optional)'
        required: false
      ak_secret:
        description: 'Access key Secret of your account (optional)'
        required: false
      # sts-token:
      #   description: 'StsToken, required in StsToken mode'
env:
  AK_ID: ${{ github.event.inputs.ak_id || secrets.AK_ID }}
  AK_SECRET: ${{ github.event.inputs.ak_secret || secrets.AK_SECRET }}
jobs:
  update_function:
    #vif: vars.BUCKET_TYPE == 'oss'
    # name: Deploying To Aliyun OSS - Node Version TODO
    runs-on: ubuntu-latest
    name: Updating Function - Aliyun
    steps:
      - name: Service & Function Names
        run: |
          echo ${{ github.event.inputs.fn_servicename }}
          echo ${{ github.event.inputs.fn_functionname }}
      - name: Install Aliyun Cli
        uses: aliyun/setup-aliyun-cli-action@v1
      - name: Update Function
        run: |
          which aliyun
          aliyun version
          command="aliyun configure set \
            --mode ${{ github.event.inputs.mode }} \
            --region ${{ github.event.inputs.region }} \
            --access-key-id $AK_ID \
            --access-key-secret $AK_SECRET"
          if [ -n "${{ github.event.inputs.sts-token }}" ]; then
            command="${command} --sts-token ${{ github.event.inputs.sts-token }}"
          fi
          $command
          # aliyun fc-open PUT /2021-04-06/services/${{ github.event.inputs.fn_servicename }}/functions/${{ github.event.inputs.fn_functionname }} --body "{\"timeout\": \"62\"}"