version: '3'
services:
  mongodb1:
   image: 'mongo:latest'
   container_name: 'mongodb1'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   ports:
     - '27017:27017'
   volumes:
     - './data/db1:/data/db'
   command: 'mongod --replSet "test" --bind_ip 0.0.0.0 --port 27017'
   restart: 'always'
  mongodb2:
   image: 'mongo:latest'
   container_name: 'mongodb2'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   ports:
     - '27018:27018'
   volumes:
     - './data/db2:/data/db'
   command: 'mongod --replSet "test" --bind_ip 0.0.0.0 --port 27018'
   restart: 'always'
  mongodb3:
   image: 'mongo:latest'
   container_name: 'mongodb3'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   ports:
     - '27019:27019'
   volumes:
     - './data/db3:/data/db'
   command: 'mongod --replSet "test" --bind_ip 0.0.0.0 --port 27019'
   restart: 'always'
  mongodb4:
   image: 'mongo:latest'
   container_name: 'mongodb4'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   ports:
     - '27020:27020'
   volumes:
     - './data/db4:/data/db'
   command: 'mongod --replSet "test" --bind_ip 0.0.0.0 --port 27020'
   restart: 'always'
  mongodb5:
   image: 'mongo:latest'
   container_name: 'mongodb5'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   ports:
     - '27021:27021'
   volumes:
     - './data/db5:/data/db'
   command: 'mongod --replSet "test" --bind_ip 0.0.0.0 --port 27021'
   restart: 'always'