version: '3.3'
services:
    ravendb:
        ports:
            - '8080:8080'
            - '38888:38888'
        volumes:
            - './data:/opt/RavenDB/Server/RavenData'
        container_name: RavenDb-WithData
        environment:
            - RAVEN_Setup_Mode=None
            - RAVEN_License_Eula_Accepted=true
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
        image: ravendb/ravendb

# docker run --rm -d -p 8080:8080 -p 38888:38888 -v c:/RavenDb/Data:/opt/RavenDB/Server/RavenData --name RavenDb-WithData -e RAVEN_Setup_Mode=None -e RAVEN_License_Eula_Accepted=true -e RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork ravendb/ravendb