/**
 * Alibaba Cloud OSS Large File Uploader (Client-Side)
 * Uses the S3-compatible API via pre-signed URLs generated by your backend.
 *
 * OSS S3-compatibility docs:
 *   https://www.alibabacloud.com/help/en/oss/developer-reference/compatibility-with-amazon-s3
 *
 * Key OSS-specific differences from AWS S3:
 *  - Endpoint format: https://<bucket>.<region>.aliyuncs.com  (path-style not needed)
 *  - Minimum multipart part size: 100KB (S3 is 5MB) — we still use 10MB for reliability
 *  - Max parts: 10,000 (same as S3)
 *  - ETag is returned without quotes in some OSS responses — we normalize this below
 *  - CORS must expose the ETag header explicitly on the OSS bucket
 *
 * Usage:
 *   const uploader = new OSSUploader({ signEndpoint: '/api/oss/sign' });
 *   const result = await uploader.upload(file, { onProgress: pct => logger.info(pct + '%') });
 */

const CHUNK_SIZE = 10 * 1024 * 1024; // 10MB per part
const MULTIPART_THRESHOLD = 5 * 1024 * 1024; // Use multipart above 5MB

import type { OSSUploaderOptions, OSSUploadOpts } from './types.ts';

class OSSUploader {
  signEndpoint: string;
  chunkSize: number;
  maxConcurrent: number;
  /**
   * @param {object} options
   * @param {string} options.signEndpoint   - Your backend endpoint for signed URL generation
   * @param {number} [options.chunkSize]    - Bytes per part (default 10MB, min 100KB for OSS)
   * @param {number} [options.maxConcurrent]- Parallel part uploads (default 3)
   */
  constructor(options: Partial<OSSUploaderOptions> = {}) {
    if (!options.signEndpoint) throw new Error('signEndpoint is required');
    this.signEndpoint = options.signEndpoint;
    this.chunkSize = options.chunkSize || CHUNK_SIZE;
    this.maxConcurrent = options.maxConcurrent || 3;
  }

  // ─── Public API ──────────────────────────────────────────────────────────────

  /**
   * Upload a File or Blob to Alibaba OSS.
   *
   * @param {File|Blob} file
   * @param {object}    [opts]
   * @param {string}    [opts.key]         - OSS object key (defaults to file.name)
   * @param {Function}  [opts.onProgress]  - Callback with integer 0–100
   * @param {AbortSignal} [opts.signal]    - AbortController signal to cancel
   * @returns {Promise<{ key: string, location: string }>}
   */
  async upload(file: File | Blob, opts: OSSUploadOpts = {}): Promise<{ key: string; location: string }> {
    const key = opts.key || (file instanceof File ? file.name : '');
    const onProgress = opts.onProgress || (() => {});
    const signal = opts.signal || null;

    if (file.size <= MULTIPART_THRESHOLD) {
      return this._singleUpload(file, key, onProgress, signal);
    }
    return this._multipartUpload(file, key, onProgress, signal);
  }

  // ─── Single-Part Upload (≤5MB) ───────────────────────────────────────────────

  async _singleUpload(
    file: File | Blob,
    key: string,
    onProgress: (pct: number) => void,
    signal: AbortSignal | null,
  ): Promise<{ key: string; location: string }> {
    onProgress(0);

    const { signedUrl, location } = await this._callBackend({
      type: 'single',
      key,
      contentType: file.type || 'application/octet-stream',
      size: file.size,
    });

    await this._putBlob(
      signedUrl,
      file,
      file.type,
      loaded => {
        onProgress(Math.round((loaded / file.size) * 100));
      },
      signal,
    );

    onProgress(100);
    return { key, location };
  }

  // ─── Multipart Upload (>5MB) ─────────────────────────────────────────────────

  async _multipartUpload(
    file: File | Blob,
    key: string,
    onProgress: (pct: number) => void,
    signal: AbortSignal | null,
  ): Promise<{ key: string; location: string }> {
    // Step 1 — Initiate: backend calls CreateMultipartUpload, returns uploadId
    const { uploadId } = await this._callBackend({
      type: 'initiate',
      key,
      contentType: file.type || 'application/octet-stream',
    });

    const chunks = this._splitFile(file);
    const partProgress = new Array(chunks.length).fill(0);

    const reportProgress = () => {
      const uploaded = partProgress.reduce((s, v) => s + v, 0);
      onProgress(Math.round((uploaded / file.size) * 100));
    };

    // Step 2 — Upload parts concurrently
    const completedParts: Array<{ PartNumber: number; ETag: string | null | undefined }> = [];
    const queue = chunks.map((chunk, i) => ({ chunk, partNumber: i + 1, index: i }));

    const worker = async () => {
      while (queue.length > 0) {
        const item = queue.shift();
        if (!item) break;
        const { chunk, partNumber, index } = item;

        if (signal?.aborted) throw new DOMException('Upload aborted', 'AbortError');

        // Get a signed URL for this specific part
        const { signedUrl } = await this._callBackend({
          type: 'part',
          key,
          uploadId,
          partNumber,
        });

        // PUT the chunk; OSS returns ETag in response header
        const rawETag = await this._putBlob(
          signedUrl,
          chunk,
          file.type || 'application/octet-stream',
          loaded => {
            partProgress[index] = loaded;
            reportProgress();
          },
          signal,
          /* returnETag= */ true,
        );

        // OSS sometimes returns ETag without surrounding quotes — normalise
        const etag = rawETag?.replace(/"/g, '') ? `"${rawETag.replace(/"/g, '')}"` : rawETag;

        completedParts.push({ PartNumber: partNumber, ETag: etag });
      }
    };

    const workers = Array.from({ length: this.maxConcurrent }, worker);
    try {
      await Promise.all(workers);
    } catch (err) {
      // Best-effort abort to avoid orphaned multipart uploads costing storage
      await this._callBackend({ type: 'abort', key, uploadId }).catch(() => {});
      throw err;
    }

    // Step 3 — Complete: parts must be sorted by PartNumber
    completedParts.sort((a, b) => a.PartNumber - b.PartNumber);

    const { location } = await this._callBackend({
      type: 'complete',
      key,
      uploadId,
      parts: completedParts,
    });

    onProgress(100);
    return { key, location };
  }

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  _splitFile(file: File | Blob): Blob[] {
    const chunks: Blob[] = [];
    for (let offset = 0; offset < file.size; offset += this.chunkSize) {
      chunks.push(file.slice(offset, offset + this.chunkSize));
    }
    return chunks;
  }

  async _callBackend(payload: Record<string, unknown>) {
    const res = await fetch(this.signEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Backend error (${res.status}): ${text}`);
    }
    return res.json();
  }

  /**
   * PUT a Blob to a pre-signed OSS URL via XHR (for upload progress events).
   *
   * OSS S3-compatible PUT requires:
   *   - Content-Type header must match the value used when signing
   *   - Do NOT send Content-MD5 unless you included it in the signed headers
   *
   * @returns {Promise<string|undefined>} ETag value when returnETag=true
   */
  _putBlob(
    signedUrl: string,
    blob: Blob,
    contentType: string,
    onProgress: (loaded: number) => void,
    signal: AbortSignal | null,
    returnETag = false,
  ): Promise<string | null | undefined> {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('PUT', signedUrl);

      // Content-Type must match what was signed on the backend
      if (contentType) xhr.setRequestHeader('Content-Type', contentType);

      xhr.upload.addEventListener('progress', e => {
        if (e.lengthComputable) onProgress(e.loaded);
      });

      xhr.addEventListener('load', () => {
        if (xhr.status >= 200 && xhr.status < 300) {
          resolve(returnETag ? xhr.getResponseHeader('ETag') : undefined);
        } else {
          // OSS returns XML error bodies — surface them for easier debugging
          reject(new Error(`OSS PUT failed (HTTP ${xhr.status}): ${xhr.responseText}`));
        }
      });

      xhr.addEventListener('error', () => reject(new Error('Network error during OSS upload')));
      xhr.addEventListener('abort', () => reject(new DOMException('Upload aborted', 'AbortError')));

      if (signal) signal.addEventListener('abort', () => xhr.abort(), { once: true });

      xhr.send(blob);
    });
  }
}

export default OSSUploader;
