/**
 * Alibaba Cloud OSS Large File Uploader (Client-Side)
 * Uses the S3-compatible API via pre-signed URLs generated by your backend.
 *
 * OSS S3-compatibility docs:
 *   https://www.alibabacloud.com/help/en/oss/developer-reference/compatibility-with-amazon-s3
 *
 * Key OSS-specific differences from AWS S3:
 *  - Endpoint format: https://<bucket>.<region>.aliyuncs.com  (path-style not needed)
 *  - Minimum multipart part size: 100KB (S3 is 5MB) — we still use 10MB for reliability
 *  - Max parts: 10,000 (same as S3)
 *  - ETag is returned without quotes in some OSS responses — we normalize this below
 *  - CORS must expose the ETag header explicitly on the OSS bucket
 *
 * Usage:
 *   const uploader = new OSSUploader({ signEndpoint: '/api/oss/sign' });
 *   const result = await uploader.upload(file, { onProgress: pct => logger.info(pct + '%') });
 *
 * Note on progress reporting with fetch:
 *   The fetch API does not natively expose upload progress (only download progress via
 *   Response.body.getReader()). To track upload progress we wrap the Blob in a
 *   ReadableStream that counts bytes as they are consumed by fetch.
 */

const CHUNK_SIZE = 10 * 1024 * 1024; // 10MB per part
const MULTIPART_THRESHOLD = 5 * 1024 * 1024; // Use multipart above 5MB

import type { OSSUploaderOptions, OSSUploadOpts } from './types.ts';

class OSSUploader {
  signEndpoint: string;
  chunkSize: number;
  maxConcurrent: number;
  /**
   * @param {object} options
   * @param {string} options.signEndpoint    - Your backend endpoint for signed URL generation
   * @param {number} [options.chunkSize]     - Bytes per part (default 10MB, min 100KB for OSS)
   * @param {number} [options.maxConcurrent] - Parallel part uploads (default 3)
   */
  constructor(options: Partial<OSSUploaderOptions> = {}) {
    if (!options.signEndpoint) throw new Error('signEndpoint is required');
    this.signEndpoint = options.signEndpoint;
    this.chunkSize = options.chunkSize || CHUNK_SIZE;
    this.maxConcurrent = options.maxConcurrent || 3;
  }

  // ─── Public API ──────────────────────────────────────────────────────────────

  /**
   * Upload a File or Blob to Alibaba OSS.
   *
   * @param {File|Blob} file
   * @param {object}    [opts]
   * @param {string}    [opts.key]          - OSS object key (defaults to file.name)
   * @param {Function}  [opts.onProgress]   - Callback with integer 0–100
   * @param {AbortSignal} [opts.signal]     - AbortController signal to cancel
   * @returns {Promise<{ key: string, location: string }>}
   */
  async upload(file: File | Blob, opts: OSSUploadOpts = {}): Promise<{ key: string; location: string }> {
    const key = opts.key || (file instanceof File ? file.name : '');
    const onProgress = opts.onProgress || (() => {});
    const signal = opts.signal || null;

    if (file.size <= MULTIPART_THRESHOLD) {
      return this._singleUpload(file, key, onProgress, signal);
    }
    return this._multipartUpload(file, key, onProgress, signal);
  }

  // ─── Single-Part Upload (≤5MB) ───────────────────────────────────────────────

  async _singleUpload(
    file: File | Blob,
    key: string,
    onProgress: (pct: number) => void,
    signal: AbortSignal | null,
  ): Promise<{ key: string; location: string }> {
    onProgress(0);

    const { signedUrl, location } = await this._callBackend({
      type: 'single',
      key,
      contentType: file.type || 'application/octet-stream',
      size: file.size,
    });

    await this._putBlob(
      signedUrl,
      file,
      file.type,
      loaded => {
        onProgress(Math.round((loaded / file.size) * 100));
      },
      signal,
    );

    onProgress(100);
    return { key, location };
  }

  // ─── Multipart Upload (>5MB) ─────────────────────────────────────────────────

  async _multipartUpload(
    file: File | Blob,
    key: string,
    onProgress: (pct: number) => void,
    signal: AbortSignal | null,
  ): Promise<{ key: string; location: string }> {
    // Step 1 — Initiate: backend calls CreateMultipartUpload, returns uploadId
    const { uploadId } = await this._callBackend({
      type: 'initiate',
      key,
      contentType: file.type || 'application/octet-stream',
    });

    const chunks = this._splitFile(file);
    const partProgress = new Array(chunks.length).fill(0);

    const reportProgress = () => {
      const uploaded = partProgress.reduce((s, v) => s + v, 0);
      onProgress(Math.round((uploaded / file.size) * 100));
    };

    // Step 2 — Upload parts concurrently
    const completedParts: Array<{ PartNumber: number; ETag: string | null | undefined }> = [];
    const queue = chunks.map((chunk, i) => ({ chunk, partNumber: i + 1, index: i }));

    const worker = async () => {
      while (queue.length > 0) {
        const item = queue.shift();
        if (!item) break;
        const { chunk, partNumber, index } = item;

        if (signal?.aborted) throw new DOMException('Upload aborted', 'AbortError');

        // Get a signed URL for this specific part
        const { signedUrl } = await this._callBackend({
          type: 'part',
          key,
          uploadId,
          partNumber,
        });

        // PUT the chunk; OSS returns ETag in response header
        const rawETag = await this._putBlob(
          signedUrl,
          chunk,
          file.type || 'application/octet-stream',
          loaded => {
            partProgress[index] = loaded;
            reportProgress();
          },
          signal,
          /* returnETag= */ true,
        );

        // OSS sometimes returns ETag without surrounding quotes — normalise
        const etag = rawETag?.replace(/"/g, '') ? `"${rawETag.replace(/"/g, '')}"` : rawETag;

        completedParts.push({ PartNumber: partNumber, ETag: etag });
      }
    };

    const workers = Array.from({ length: this.maxConcurrent }, worker);
    try {
      await Promise.all(workers);
    } catch (err) {
      // Best-effort abort to avoid orphaned multipart uploads costing storage
      await this._callBackend({ type: 'abort', key, uploadId }).catch(() => {});
      throw err;
    }

    // Step 3 — Complete: parts must be sorted by PartNumber
    completedParts.sort((a, b) => a.PartNumber - b.PartNumber);

    const { location } = await this._callBackend({
      type: 'complete',
      key,
      uploadId,
      parts: completedParts,
    });

    onProgress(100);
    return { key, location };
  }

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  _splitFile(file: File | Blob): Blob[] {
    const chunks: Blob[] = [];
    for (let offset = 0; offset < file.size; offset += this.chunkSize) {
      chunks.push(file.slice(offset, offset + this.chunkSize));
    }
    return chunks;
  }

  async _callBackend(payload: Record<string, unknown>) {
    const res = await fetch(this.signEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Backend error (${res.status}): ${text}`);
    }
    return res.json();
  }

  /**
   * PUT a Blob to a pre-signed OSS URL using the fetch API.
   *
   * Upload progress is tracked by wrapping the Blob in a ReadableStream that
   * counts bytes as they pass through, since fetch does not expose an upload
   * progress event like XHR does.
   *
   * OSS S3-compatible PUT requires:
   *   - Content-Type header must match the value used when signing
   *   - Do NOT send Content-MD5 unless you included it in the signed headers
   *
   * @param {string}      signedUrl
   * @param {Blob}        blob
   * @param {string}      contentType
   * @param {Function}    onProgress   - Called with bytes uploaded so far
   * @param {AbortSignal|null} signal
   * @param {boolean}     returnETag   - If true, resolves with the ETag header value
   * @returns {Promise<string|undefined>}
   */
  async _putBlob(
    signedUrl: string,
    blob: Blob,
    contentType: string,
    onProgress: (loaded: number) => void,
    signal: AbortSignal | null,
    returnETag = false,
  ): Promise<string | null | undefined> {
    const totalBytes = blob.size;
    let uploadedBytes = 0;

    // Wrap the blob's byte stream so we can intercept each chunk and report progress.
    // fetch() cannot report upload progress on its own — this is the standard workaround.
    const progressStream = new ReadableStream({
      async start(controller) {
        const reader = blob.stream().getReader();
        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) {
              controller.close();
              break;
            }
            uploadedBytes += value.byteLength;
            onProgress(uploadedBytes);
            controller.enqueue(value);
          }
        } catch (err) {
          controller.error(err);
        }
      },
    });

    const headers = {};
    if (contentType) headers['Content-Type'] = contentType;

    // Content-Length must be set explicitly — fetch cannot infer it from a
    // ReadableStream, and OSS requires it for multipart PUT requests.
    headers['Content-Length'] = String(totalBytes);

    // biome-ignore lint/suspicious/noImplicitAnyLet: assigned in try/catch below
    let response;
    try {
      // duplex:'half' is required for streaming bodies (Chrome 105+, Firefox 112+) but missing from TypeScript's RequestInit
      const fetchOpts: RequestInit & { duplex?: string } = {
        method: 'PUT',
        headers,
        body: progressStream,
        signal,
        duplex: 'half',
      };
      response = await fetch(signedUrl, fetchOpts);
    } catch (err) {
      const e = err as Error;
      if (e.name === 'AbortError') throw new DOMException('Upload aborted', 'AbortError');
      throw new Error(`Network error during OSS upload: ${e.message}`);
    }

    if (!response.ok) {
      // OSS returns XML error bodies — surface them for easier debugging
      const text = await response.text().catch(() => '');
      throw new Error(`OSS PUT failed (HTTP ${response.status}): ${text}`);
    }

    return returnETag ? response.headers.get('ETag') : undefined;
  }
}

export default OSSUploader;
