# apiVersion: v1
# kind: Service
# metadata:
#   name: web2
#   namespace: default
# spec:
#   ports:
#   - port: 3000
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     run: web2
#   type: NodePort
