kind: Job
apiVersion: batch/v1
metadata:
  name: job-jobx
  namespace: <project name>
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0 # retries
  # activeDeadlineSeconds: 120 # how long pod can run
  ttlSecondsAfterFinished: 10
  selector: {}
  template:
    metadata:
      name: jobx-job-spec
    spec:
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 600M
            requests:
              cpu: 100m
              memory: 200M
          # terminationMessagePath: /dev/termination-log
          name: jobx-job-container
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              python -u hello.py
            # python main.py && sleep 20s && touch /tmp/pod/terminated
            # use ttlSecondsAfterFinished instead of sleep
            # touch /tmp/pod/terminated is for sidecar
          env:
            - name: ENTRY_POINT
              value: python app.py
            - name: SLEEP_S
              value: "2"
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'cr/project(or ns)/repo:tag'
      restartPolicy: Never
