openapi: 3.0.0
info:
  version: 1.0.0
  title: Cookbook API
  description: A sample API to demonstrate features in the OpenAPI specification
  termsOfService: http://es-labs.org/terms/
  contact:
    name: ES-Labs API Team
    email: eslabs.com@gmail.com
    url: https://es-labs.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Auth
    description: authentication api
  - name: Base
    description: basic api
servers:
  - url: http://127.0.0.1:3000/api
    description: local development server
  - url: '{protocol}://{environment}.example.com/v2'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api         # Production server
          - api.dev     # Development server
          - api.staging # Staging server
components:
  securitySchemes:
    BasicAuth:
      $ref: 'http://127.0.0.1:8080/openapi/securitySchema.yaml#/MySecurity/BasicAuth'
    ApiKeyAuth:
      $ref: 'http://127.0.0.1:8080/openapi/securitySchema.yaml#/MySecurity/ApiKeyAuth'
  schemas:
    Error:
      $ref: 'http://127.0.0.1:8080/openapi/objects.yaml#/components/schemas/Error'

security:
  - BasicAuth: []
  - ApiKeyAuth: []

paths:
  /healthcheck:
    $ref: 'http://127.0.0.1:8080/openapi/base.yaml#healthcheck'
  /health-auth:
    $ref: 'http://127.0.0.1:8080/openapi/base.yaml#health-auth'
  /upload-disk:
    $ref: 'http://127.0.0.1:8080/openapi/base.yaml#upload-disk'
  /auth/login:
    $ref: 'http://127.0.0.1:8080/openapi/auth.yaml#login'
  /auth/otp:
    $ref: 'http://127.0.0.1:8080/openapi/auth.yaml#otp'
  /categories:
    $ref: 'http://127.0.0.1:8080/openapi/categories.yaml#no-id'
  /categories/{id}:
    $ref: 'http://127.0.0.1:8080/openapi/categories.yaml#with-id'
