# model studio
# sk-a58a4a2ea6144df4b8b2b3793027e356

@mcp-api = https://dev-mcp.visiongroup.co:3337
# @mcp-api = https://8.219.4.102:3337
# @mcp-api = https://127.0.0.1:3337

@session = ae5800b5-d809-4a2c-87f3-4aa6b8e63be1

### Status
GET {{mcp-api}}/status

### Init
POST {{mcp-api}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Authorization: Bearer my-secret-token

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
      "protocolVersion": "2025-06-18",
      "capabilities": { "interactive": true },
      "clientInfo": { "name": "example-client", "version": "1.0.0" }
    }
}

### List Tools - 
POST {{mcp-api}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{session}}

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {
    "cursor": "optional-cursor-value"
  }
}

### Call Echo tool
POST {{mcp-api}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{session}}
Authorization: Bearer my-secret-token

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "echo",
    "arguments": {
      "message": "Hello ABC"
    }
  }
}

### Call BMI tool
POST {{mcp-api}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{session}}
Authorization: Bearer my-secret-token

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "calculate-bmi",
    "arguments": {
      "weightKg": 70,
      "heightM": 1.75
    }
  }
}

### Call Due Date tool
POST {{mcp-api}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: {{session}}
Authorization: Bearer my-secret-token

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "days-to-due-date",
    "arguments": {
      "calcDate": "2000-01-01",
      "dueDate": "2000-01-02"
    }
  }
}
