name: '(NEW) Deploy the Application'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'dev'
      target:
        description: 'Select deployment target'
        required: true
        type: choice
        options:
          - dev
          - stg
      namespace:
        description: 'Dev Namespace'
        required: false
        default: 'default'

  pull_request:
    types: [closed]
    branches:
      - prd

jobs:
  set-matrix:
    name: Set Matrix for Deployment
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix || steps.set-matrix-pr.outputs.matrix }}
      branch: ${{ steps.set-matrix.outputs.branch || steps.set-matrix-pr.outputs.branch }}
      environment: ${{ steps.set-matrix.outputs.environment || steps.set-matrix-pr.outputs.environment }}
    steps:
      - name: Set matrix for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        id: set-matrix
        run: |
          if [ "${{ github.event.inputs.branch }}" == "prd" ]; then
            echo "❌ You cannot deploy from the 'prd' branch using workflow_dispatch."
            exit 1
          fi
          echo "matrix={\"target\":[\"${{ github.event.inputs.target }}\"]}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          echo "environment=${{ github.event.inputs.target }}" >> $GITHUB_OUTPUT
      - name: Set matrix for pull_request on prd branch and closed
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/prd'
        id: set-matrix-pr
        run: |
          echo 'matrix={"target":["prd"]}' >> $GITHUB_OUTPUT
          echo 'branch=prd' >> $GITHUB_OUTPUT
          echo 'environment=prd' >> $GITHUB_OUTPUT

  build_push_deploy:
    name: Build, Push and Deploy (${{ matrix.target }})
    needs: set-matrix
    if: needs.set-matrix.outputs.matrix != ''
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    environment: ${{ matrix.target }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.set-matrix.outputs.branch }}
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Set Image Tag
        id: imgtag
        run: |
          ROLLING_BUILD_NUM=$((GITHUB_RUN_NUMBER % 100))
          TAG="v${{ steps.date.outputs.date }}${ROLLING_BUILD_NUM}"
          IMAGE="${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}:$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
      - name: Set Doppler Config
        id: dopplerconfig
        run: |
          if [ "${{ matrix.target }}" = "dev" ]; then
            if [ "${{ github.event.inputs.namespace }}" = "default" ]; then
              CONFIG="${{ vars.DOPPLER_CONFIG_KEY }}"
            else
              CONFIG="${{ vars.DOPPLER_CONFIG_KEY }}_${{ github.event.inputs.namespace }}"
            fi
          else
            CONFIG="${{ vars.DOPPLER_CONFIG_KEY }}"
          fi
          echo "config=$CONFIG" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
          --build-arg ARG_NODE_ENV=${{ needs.set-matrix.outputs.environment }} \
          --build-arg ARG_DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} \
          --build-arg ARG_DOPPLER_PROJECT=${{ vars.PROJECT_NAME }} \
          --build-arg ARG_DOPPLER_CONFIG=${{ vars.DOPPLER_CONFIG_KEY }} \
          -t ${{ steps.imgtag.outputs.image }} .
      - name: Set up Docker credentials
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ vars.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ steps.imgtag.outputs.image }}
      - name: Checkout CI/CD repo
        if: matrix.target == 'dev'
        uses: actions/checkout@v6
        with:
          repository: ais-one/<something>
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: cicd
      - name: Deploy to Kubernetes
        if: matrix.target == 'dev'
        env:
          NAMESPACE: ${{ github.event.inputs.namespace }}
          BUILD_VERSION: ${{ steps.imgtag.outputs.tag }}
          IMAGE: ${{ steps.imgtag.outputs.image }}
        run: |
          export KUBECONFIG=$(pwd)/cicd/k8s/kubeconfig-dev.yaml
          kubectl cluster-info
          envsubst < cicd/k8s/backend-mcp/0-namespace.yaml | kubectl apply -f -
          kubectl create secret docker-registry acr-secret --docker-server=${{ vars.REGISTRY_URL }} --docker-username=${{ secrets.REGISTRY_USER }} --docker-password=${{ secrets.REGISTRY_PASSWORD }} --docker-email=aaronjxz@gmail.com -n ${{ github.event.inputs.namespace }} || true
          envsubst < cicd/k8s/backend-mcp/1-deployment.yaml | kubectl apply -f -
          envsubst < cicd/k8s/backend-mcp/2-service.yaml | kubectl apply -f -
          envsubst < cicd/k8s/backend-mcp/3-ingressroute.yaml | kubectl apply -f -
      - name: Install Serverless Devs
        if: matrix.target == 'stg' || github.event_name == 'pull_request'
        run: npm install -g @serverless-devs/s
      - name: Configure Serverless Devs
        if: matrix.target == 'stg' || github.event_name == 'pull_request'
        run: |
          s config add --AccessKeyID ${{ secrets.ALIYUN_ACCESS_KEY_ID }} --AccessKeySecret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} -a alias-cicd
      - name: Deploy to FC with alias
        if: matrix.target == 'stg' || github.event_name == 'pull_request'
        env:
          IMAGE_NAME: ${{ vars.REGISTRY_URL_DEPLOY }}/${{ vars.REGISTRY_PATH }}:${{ steps.imgtag.outputs.tag }}
          BUILD_VERSION: ${{ steps.imgtag.outputs.tag }}
        run: |
          envsubst < ./.aliyun/fc/${{ matrix.target }}.yaml > /tmp/processed_template.yaml
          s deploy --template /tmp/processed_template.yaml --use-local --assume-yes
      - name: Add image info to job summary
        run: |
          echo "## 🚀 Deployment Info" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Version:** \`${{ steps.imgtag.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Target:** \`${{ matrix.target }}\`" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.target }}" == "dev" ]; then
            # If target is dev, replace {{NAMESPACE}} inside CHECK_URL with the provided namespace
            check_url=$(echo '${{ vars.CHECK_URL }}' | sed 's/{{NAMESPACE}}/${{ github.event.inputs.namespace }}/g')
            echo "- **Check URL:** [$check_url]($check_url)" >> $GITHUB_STEP_SUMMARY
          else
            # Otherwise, just output CHECK_URL as is
            echo "- **Check URL:** [${{ vars.CHECK_URL }}](${{ vars.CHECK_URL }})" >> $GITHUB_STEP_SUMMARY
          fi
